import type { SupplierSnapshot } from './types';

export const SC_SUPPLIERS: SupplierSnapshot[] = [
  {
    supplierId: 'GOTION',
    nameEn: 'Gotion High-Tech',
    nameZh: '国轩高科',
    tier: 'Tier 1',
    country: 'China',
    countryZh: '中国',
    component: 'Battery Cells & Packs',
    componentZh: '电池电芯与电池包',
    programs: ['ID.UNYX', 'ID.CODE'],
    sRating: 'B',
    awardStatus: 'Conditional',
    certifications: [
      { name: 'ISO 14001', status: 'Active', validUntil: '2026-03-15' },
      { name: 'IATF 16949', status: 'Active', validUntil: '2025-11-30' },
      { name: 'ISO 50001', status: 'In Progress' },
      { name: 'EMAS', status: 'Missing' },
    ],
    latestEmissionQ: 'Q4 2024',
    latestScope1: 340,
    latestScope2: 550,
    emissionTrend: 'Stable',
    batteryPassport: {
      completenessPercent: 60,
      requiredFields: [
        { fieldNameEn: 'Cell Supplier Identity', fieldNameZh: '电芯供应商信息', status: 'Complete' },
        { fieldNameEn: 'Pack Supplier Identity', fieldNameZh: '电池包供应商信息', status: 'Complete' },
        { fieldNameEn: 'Battery Chemistry', fieldNameZh: '电池化学成分', status: 'Complete' },
        { fieldNameEn: 'Manufacturing Plant', fieldNameZh: '制造工厂', status: 'Complete' },
        { fieldNameEn: 'Upstream Chain Coverage', fieldNameZh: '上游供应链覆盖', status: 'Incomplete', owner: 'Gotion Procurement', notes: 'Cobalt origin missing for Tier 2' },
        { fieldNameEn: 'Carbon Footprint (g CO2/kWh)', fieldNameZh: '碳足迹 (g CO2/kWh)', status: 'Incomplete', owner: 'Gotion ESG', notes: 'Scope 3 data not provided' },
        { fieldNameEn: 'Recycled Content Evidence', fieldNameZh: '回收材料证明', status: 'Missing', owner: 'Gotion Procurement', notes: 'No recycled lithium evidence submitted' },
        { fieldNameEn: 'Conflict Mineral Declaration', fieldNameZh: '冲突矿产声明', status: 'Incomplete', owner: 'VW Supply Chain', notes: 'Cobalt sourcing from DRC flagged' },
        { fieldNameEn: 'End-of-Life Plan', fieldNameZh: '报废计划', status: 'Complete' },
        { fieldNameEn: 'Safety Data Sheet', fieldNameZh: '安全数据表', status: 'Complete' },
        { fieldNameEn: 'State of Health (SoH) Protocol', fieldNameZh: '健康状态协议', status: 'Missing' },
        { fieldNameEn: 'EU Battery Passport Compliance', fieldNameZh: '欧盟电池护照合规', status: 'Missing', notes: 'Not initiated — blocks EU market access' },
      ],
      cellSupplier: 'Gotion High-Tech (合肥)',
      packSupplier: 'Gotion High-Tech (合肥)',
      chemistry: 'LFP (Lithium Iron Phosphate)',
      plantCountry: 'China (Hefei, Anhui)',
      upstreamCoveragePercent: 45,
      carbonFootprintComplete: false,
      recycledContentEvidenced: false,
      euPassportReady: false,
    },
    activeRisks: [
      {
        id: 'RISK_GOTION_001',
        category: 'Human Rights',
        level: 'High',
        titleEn: 'Cobalt Upstream Traceability Gap',
        titleZh: '钴矿上游溯源缺口',
        descriptionEn: 'Gotion sources cobalt from Tier 2 supplier with DRC (Democratic Republic of Congo) exposure. No conflict mineral audit completed. Blocks EU Battery Regulation compliance.',
        descriptionZh: '国轩从有刚果民主共和国采购记录的二级供应商购买钴矿，未完成冲突矿产审计，阻碍欧盟电池法规合规。',
        detectedDate: '2024-11-15',
        programs: ['ID.UNYX', 'ID.CODE'],
      },
      {
        id: 'RISK_GOTION_002',
        category: 'Single Source',
        level: 'Medium',
        titleEn: 'Single Source for LFP Cells',
        titleZh: 'LFP电芯单一来源依赖',
        descriptionEn: 'Gotion is the sole cell supplier for both China NEV programs. No qualified second source. Any quality or capacity issue creates program delay.',
        descriptionZh: '国轩是两个中国新能源汽车项目的唯一电芯供应商，无合格备用来源，任何质量或产能问题均可导致项目延迟。',
        detectedDate: '2024-09-01',
        programs: ['ID.UNYX', 'ID.CODE'],
      },
    ],
    correctiveActions: [
      {
        actionId: 'CA_GOTION_001',
        titleEn: 'Submit Cobalt Origin Documentation',
        titleZh: '提交钴矿来源文件',
        descriptionEn: 'Provide full chain-of-custody certificates for all cobalt used in LFP cells supplied to VW China programs.',
        descriptionZh: '提供供应给大众中国项目的所有LFP电芯中钴的完整监管链证书。',
        status: 'Open',
        dueDate: '2025-04-30',
        ownerEn: 'Gotion Procurement VP',
        ownerZh: '国轩采购副总裁',
        priority: 'Critical',
        blocksAward: true,
      },
      {
        actionId: 'CA_GOTION_002',
        titleEn: 'Complete EU Battery Passport Fields 7–12',
        titleZh: '完成欧盟电池护照第7-12项',
        descriptionEn: 'Fill recycled content evidence, Scope 3 carbon footprint, and SoH protocol fields in the EU Battery Regulation digital passport.',
        descriptionZh: '在欧盟电池法规数字护照中填写回收材料证明、范围3碳足迹和健康状态协议字段。',
        status: 'In Progress',
        dueDate: '2025-05-15',
        ownerEn: 'Gotion ESG Team',
        ownerZh: '国轩ESG团队',
        priority: 'High',
        blocksAward: true,
      },
    ],
    recentEvents: [
      {
        eventId: 'EVT_G_001',
        timestamp: '2025-02-10T09:00:00Z',
        type: 'SupplierRiskDetectedEvent',
        supplierId: 'GOTION',
        riskCategory: 'Human Rights',
        riskLevel: 'High',
        descriptionEn: 'DRC cobalt sourcing identified in Tier 2 audit',
        descriptionZh: '二级审计发现刚果(金)钴矿采购问题',
        detectedBy: 'VW Supply Chain Audit',
      },
      {
        eventId: 'EVT_G_002',
        timestamp: '2025-01-20T14:30:00Z',
        type: 'SupplierEmissionReportedEvent',
        supplierId: 'GOTION',
        quarter: 'Q4 2024',
        scope1tCO2e: 340,
        scope2tCO2e: 550,
        reportedBy: 'Gotion ESG Team',
      },
      {
        eventId: 'EVT_G_003',
        timestamp: '2025-03-01T11:00:00Z',
        type: 'BatteryTraceabilityUpdatedEvent',
        supplierId: 'GOTION',
        fieldUpdated: 'Manufacturing Plant',
        oldCompleteness: 55,
        newCompleteness: 60,
        notes: 'Plant address and capacity data confirmed for Hefei facility',
      },
    ],
    lastUpdated: '2025-03-10',
  },

  {
    supplierId: 'CATL',
    nameEn: 'CATL',
    nameZh: '宁德时代',
    tier: 'Tier 1',
    country: 'China',
    countryZh: '中国',
    component: 'Battery Cells (NMC)',
    componentZh: '电池电芯（三元锂）',
    programs: ['ID.CODE'],
    sRating: 'A',
    awardStatus: 'Award Ready',
    certifications: [
      { name: 'ISO 14001', status: 'Active', validUntil: '2026-08-01' },
      { name: 'IATF 16949', status: 'Active', validUntil: '2026-06-30' },
      { name: 'ISO 50001', status: 'Active', validUntil: '2025-12-31' },
      { name: 'EMAS', status: 'Active', validUntil: '2026-01-15' },
    ],
    latestEmissionQ: 'Q4 2024',
    latestScope1: 480,
    latestScope2: 720,
    emissionTrend: 'Improving',
    batteryPassport: {
      completenessPercent: 85,
      requiredFields: [
        { fieldNameEn: 'Cell Supplier Identity', fieldNameZh: '电芯供应商信息', status: 'Complete' },
        { fieldNameEn: 'Pack Supplier Identity', fieldNameZh: '电池包供应商信息', status: 'Complete' },
        { fieldNameEn: 'Battery Chemistry', fieldNameZh: '电池化学成分', status: 'Complete' },
        { fieldNameEn: 'Manufacturing Plant', fieldNameZh: '制造工厂', status: 'Complete' },
        { fieldNameEn: 'Upstream Chain Coverage', fieldNameZh: '上游供应链覆盖', status: 'Complete' },
        { fieldNameEn: 'Carbon Footprint (g CO2/kWh)', fieldNameZh: '碳足迹 (g CO2/kWh)', status: 'Complete' },
        { fieldNameEn: 'Recycled Content Evidence', fieldNameZh: '回收材料证明', status: 'Complete' },
        { fieldNameEn: 'Conflict Mineral Declaration', fieldNameZh: '冲突矿产声明', status: 'Complete' },
        { fieldNameEn: 'End-of-Life Plan', fieldNameZh: '报废计划', status: 'Complete' },
        { fieldNameEn: 'Safety Data Sheet', fieldNameZh: '安全数据表', status: 'Complete' },
        { fieldNameEn: 'State of Health (SoH) Protocol', fieldNameZh: '健康状态协议', status: 'Incomplete', notes: 'Remote SoH monitoring not yet integrated' },
        { fieldNameEn: 'EU Battery Passport Compliance', fieldNameZh: '欧盟电池护照合规', status: 'Incomplete', notes: 'In review — expected complete Q2 2025' },
      ],
      cellSupplier: 'CATL (Ningde, Fujian)',
      packSupplier: 'CATL (Liyang, Jiangsu)',
      chemistry: 'NMC 811',
      plantCountry: 'China (Fujian, Jiangsu)',
      upstreamCoveragePercent: 82,
      carbonFootprintComplete: true,
      recycledContentEvidenced: true,
      euPassportReady: false,
    },
    activeRisks: [
      {
        id: 'RISK_CATL_001',
        category: 'Financial',
        level: 'Low',
        titleEn: 'NMC Premium vs LFP Cost Position',
        titleZh: 'NMC成本溢价 vs LFP',
        descriptionEn: 'CATL NMC cells carry 12-15% cost premium vs Gotion LFP. Acceptable for ID.CODE performance segment, but increases BEV program cost.',
        descriptionZh: '宁德时代NMC电芯比国轩LFP高出12-15%成本溢价，对于ID.CODE性能细分市场可接受，但会增加新能源汽车项目成本。',
        detectedDate: '2024-10-01',
        programs: ['ID.CODE'],
      },
    ],
    correctiveActions: [
      {
        actionId: 'CA_CATL_001',
        titleEn: 'Complete SoH Remote Monitoring Integration',
        titleZh: '完成远程SoH监控集成',
        descriptionEn: 'Integrate CATL BMS with VW telematics to enable continuous battery state-of-health reporting per EU Battery Regulation requirement.',
        descriptionZh: '将宁德时代BMS与大众远程信息处理集成，按欧盟电池法规要求实现持续电池健康状态报告。',
        status: 'In Progress',
        dueDate: '2025-06-30',
        ownerEn: 'VW Digital Team + CATL BMS',
        ownerZh: '大众数字化团队 + 宁德时代BMS',
        priority: 'Medium',
        blocksAward: false,
      },
    ],
    recentEvents: [
      {
        eventId: 'EVT_C_001',
        timestamp: '2025-02-28T10:00:00Z',
        type: 'SupplierSustainabilityRatingUpdatedEvent',
        supplierId: 'CATL',
        oldRating: 'A',
        newRating: 'A',
        assessedBy: 'VW Group S-Rating Assessment',
        notes: 'Maintained A rating. Carbon footprint reporting exemplary.',
      },
      {
        eventId: 'EVT_C_002',
        timestamp: '2025-01-15T09:00:00Z',
        type: 'SupplierEmissionReportedEvent',
        supplierId: 'CATL',
        quarter: 'Q4 2024',
        scope1tCO2e: 480,
        scope2tCO2e: 720,
        reportedBy: 'CATL Sustainability Dept',
      },
    ],
    lastUpdated: '2025-03-01',
  },

  {
    supplierId: 'HORIZON',
    nameEn: 'Horizon Robotics',
    nameZh: '地平线机器人',
    tier: 'Tier 1',
    country: 'China',
    countryZh: '中国',
    component: 'ADAS System-on-Chip (Journey 6)',
    componentZh: 'ADAS芯片（征程6）',
    programs: ['ID.UNYX'],
    sRating: 'Not Assessed',
    awardStatus: 'Not Ready',
    certifications: [
      { name: 'IATF 16949', status: 'Active', validUntil: '2026-04-01' },
      { name: 'ISO 14001', status: 'Missing' },
      { name: 'ISO 26262 (ASIL-B)', status: 'In Progress' },
    ],
    latestEmissionQ: 'Q4 2024',
    latestScope1: 0,
    latestScope2: 0,
    emissionTrend: 'Not Reported',
    activeRisks: [
      {
        id: 'RISK_HORIZON_001',
        category: 'Environmental',
        level: 'High',
        titleEn: 'No S-Rating Assessment Completed',
        titleZh: '未完成S-评级评估',
        descriptionEn: 'Horizon Robotics has not undergone VW Group S-Rating assessment. S-Rating is a mandatory gate for contract award. Blocks ID.UNYX sourcing decision.',
        descriptionZh: '地平线机器人尚未接受大众集团S-评级评估。S-评级是合同授予的强制门槛，阻碍ID.UNYX采购决策。',
        detectedDate: '2024-12-01',
        programs: ['ID.UNYX'],
      },
      {
        id: 'RISK_HORIZON_002',
        category: 'Geopolitical',
        level: 'Medium',
        titleEn: 'US Export Control Exposure',
        titleZh: '美国出口管制风险',
        descriptionEn: 'Horizon Robotics uses semiconductor IP potentially affected by US export controls. Risk of supply disruption if restrictions tighten.',
        descriptionZh: '地平线机器人使用可能受美国出口管制影响的半导体知识产权，若限制收紧，存在供应中断风险。',
        detectedDate: '2025-01-10',
        programs: ['ID.UNYX'],
      },
    ],
    correctiveActions: [
      {
        actionId: 'CA_HORIZON_001',
        titleEn: 'Initiate S-Rating Assessment Process',
        titleZh: '启动S-评级评估流程',
        descriptionEn: 'Submit Horizon Robotics to VW Group S-Rating assessment. Minimum score B required for contract award eligibility.',
        descriptionZh: '提交地平线机器人接受大众集团S-评级评估，合同授予资格要求最低B级。',
        status: 'Open',
        dueDate: '2025-04-15',
        ownerEn: 'VW China Procurement Lead',
        ownerZh: '大众中国采购负责人',
        priority: 'Critical',
        blocksAward: true,
      },
      {
        actionId: 'CA_HORIZON_002',
        titleEn: 'Submit ISO 14001 Certification Plan',
        titleZh: '提交ISO 14001认证计划',
        descriptionEn: 'Horizon to submit environmental management certification roadmap with target completion date.',
        descriptionZh: '地平线提交环境管理认证路线图及目标完成日期。',
        status: 'Open',
        dueDate: '2025-05-01',
        ownerEn: 'Horizon Robotics ESG',
        ownerZh: '地平线机器人ESG',
        priority: 'High',
        blocksAward: false,
      },
    ],
    recentEvents: [
      {
        eventId: 'EVT_H_001',
        timestamp: '2025-01-10T15:00:00Z',
        type: 'SupplierRiskDetectedEvent',
        supplierId: 'HORIZON',
        riskCategory: 'Geopolitical',
        riskLevel: 'Medium',
        descriptionEn: 'US export control exposure identified for Journey 6 chipset',
        descriptionZh: '发现征程6芯片组的美国出口管制风险',
        detectedBy: 'VW Legal & Compliance',
      },
    ],
    lastUpdated: '2025-02-20',
  },

  {
    supplierId: 'VALEO_SH',
    nameEn: 'Valeo (Shanghai)',
    nameZh: '法雷奥（上海）',
    tier: 'Tier 1',
    country: 'China',
    countryZh: '中国',
    component: 'Climate Control & Local Modules',
    componentZh: '空调系统与本地化模块',
    programs: ['ID.UNYX', 'ID.CODE'],
    sRating: 'A',
    awardStatus: 'Award Ready',
    certifications: [
      { name: 'ISO 14001', status: 'Active', validUntil: '2026-09-01' },
      { name: 'IATF 16949', status: 'Active', validUntil: '2026-07-31' },
      { name: 'ISO 50001', status: 'Active', validUntil: '2025-09-30' },
    ],
    latestEmissionQ: 'Q4 2024',
    latestScope1: 85,
    latestScope2: 235,
    emissionTrend: 'Improving',
    activeRisks: [],
    correctiveActions: [],
    recentEvents: [
      {
        eventId: 'EVT_V_001',
        timestamp: '2025-02-01T08:00:00Z',
        type: 'SupplierSustainabilityRatingUpdatedEvent',
        supplierId: 'VALEO_SH',
        oldRating: 'A',
        newRating: 'A',
        assessedBy: 'VW Group S-Rating Assessment',
        notes: 'Maintained A rating. Strong local sourcing and emission reduction plan.',
      },
    ],
    lastUpdated: '2025-02-15',
  },

  {
    supplierId: 'GANFENG',
    nameEn: 'Ganfeng Lithium',
    nameZh: '赣锋锂业',
    tier: 'Tier 2',
    country: 'China',
    countryZh: '中国',
    component: 'Lithium (upstream via Gotion)',
    componentZh: '锂矿（通过国轩上游）',
    programs: ['ID.UNYX', 'ID.CODE'],
    sRating: 'Not Assessed',
    awardStatus: 'Conditional',
    certifications: [
      { name: 'ISO 14001', status: 'Active', validUntil: '2025-12-31' },
      { name: 'IRMA Standard', status: 'In Progress' },
    ],
    latestEmissionQ: 'Q3 2024',
    latestScope1: 620,
    latestScope2: 890,
    emissionTrend: 'Worsening',
    activeRisks: [
      {
        id: 'RISK_GANFENG_001',
        category: 'Human Rights',
        level: 'Medium',
        titleEn: 'Argentina Mining Operations — Labour Conditions',
        titleZh: '阿根廷矿业作业—劳工条件',
        descriptionEn: 'Ganfeng\'s Lithium Americas partnership in Jujuy, Argentina has received NGO scrutiny regarding indigenous community consultation. Potential human-rights flag under EU CSDDD.',
        descriptionZh: '赣锋锂业与Lithium Americas在阿根廷胡胡伊省的合作矿山因原住民社区协商问题受到NGO关注，可能触发欧盟企业可持续发展尽职调查指令(CSDDD)中的人权标志。',
        detectedDate: '2025-01-20',
        programs: ['ID.UNYX', 'ID.CODE'],
      },
      {
        id: 'RISK_GANFENG_002',
        category: 'Environmental',
        level: 'Medium',
        titleEn: 'Rising Scope 1 Emissions from Lithium Processing',
        titleZh: '锂矿加工范围1排放上升',
        descriptionEn: 'Q3 2024 emissions increased 18% vs Q3 2023. Lithium hydroxide conversion is energy-intensive. Conflicts with VW Scope 3 reduction targets.',
        descriptionZh: '2024年Q3排放量较2023年Q3上升18%，氢氧化锂转换能耗高，与大众集团范围3减排目标冲突。',
        detectedDate: '2024-12-15',
        programs: ['ID.UNYX', 'ID.CODE'],
      },
    ],
    correctiveActions: [
      {
        actionId: 'CA_GANFENG_001',
        titleEn: 'Commission Argentina Mining Human-Rights Audit',
        titleZh: '委托阿根廷矿山人权审计',
        descriptionEn: 'Engage independent auditor (e.g., Responsible Business Alliance) to assess Ganfeng Argentina operations for CSDDD compliance.',
        descriptionZh: '聘请独立审计师（如责任商业联盟）评估赣锋锂业阿根廷运营的CSDDD合规性。',
        status: 'Open',
        dueDate: '2025-06-30',
        ownerEn: 'VW Sustainability Team',
        ownerZh: '大众可持续发展团队',
        priority: 'High',
        blocksAward: false,
      },
    ],
    recentEvents: [
      {
        eventId: 'EVT_GF_001',
        timestamp: '2025-01-20T12:00:00Z',
        type: 'SupplierRiskDetectedEvent',
        supplierId: 'GANFENG',
        riskCategory: 'Human Rights',
        riskLevel: 'Medium',
        descriptionEn: 'NGO report on Argentina mining community consultation published',
        descriptionZh: '阿根廷矿山社区协商NGO报告发布',
        detectedBy: 'VW External Monitoring',
      },
    ],
    lastUpdated: '2025-02-05',
  },
];
