import type { ChinaCmpProgramSnapshot } from './types';

// EUR_PER_PP: Each percentage point of cost reduction ≈ €20M/year at current volumes
const EUR_PER_PP = 20;

// ─── ID.UNYX Program ─────────────────────────────────────────────────────────

const ID_UNYX: ChinaCmpProgramSnapshot = {
  program: 'id-unyx-cmp',
  programNameEn: 'ID.UNYX CMP',
  programNameZh: 'ID.UNYX 成本平价计划',
  targetCostReductionPct: 40,
  currentCostReductionPct: 28,
  gapPct: 12,
  gapEurM: 12 * EUR_PER_PP,
  status: 'Amber',
  varianceLast30Days: -1,
  marginAtRisk90Days: 1.8,
  marginAtRiskEurM: 1.8 * EUR_PER_PP,
  sopDate: '2026-09-15',
  biggestLeverEn: 'Gotion battery renegotiation — closing the 4pp battery gap would eliminate 33% of the total program gap in 2 weeks.',
  biggestLeverZh: '国轩高科电池重新谈判——弥补4个百分点的电池缺口将在2周内消除项目总缺口的33%。',
  lastUpdated: '2026-03-15T09:00:00Z',
  costDriverBreakdown: {
    battery: {
      achieved: -8,
      needed: -12,
      status: 'Amber',
      recentEvents: [
        {
          eventId: 'evt-001',
          timestamp: '2026-02-15T08:30:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'gotion-high-tech',
          supplierNameEn: 'Gotion High-Tech',
          supplierNameZh: '国轩高科',
          componentCategory: 'Battery',
          oldCostIndex: 100,
          newCostIndex: 103,
          costDeltaPct: +3,
          reasonCode: 'raw-material-inflation',
          reasonEn: 'Lithium carbonate spot price rose 18% in Q1 2026, increasing cell production costs. Gotion citing force majeure on raw material clause.',
          reasonZh: '碳酸锂现货价格在2026年Q1上涨18%，推高了电芯生产成本。国轩高科引用原材料条款中的不可抗力。',
          effectiveDate: '2026-02-15',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-002',
          timestamp: '2026-03-01T11:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'gotion-high-tech',
          supplierNameEn: 'Gotion High-Tech',
          supplierNameZh: '国轩高科',
          componentCategory: 'Battery',
          oldCostIndex: 97,
          newCostIndex: 103,
          costDeltaPct: +2,
          reasonCode: 'volume-discount-claw-back',
          reasonEn: 'Negotiated volume discount clawed back due to production ramp delay at Anting plant. Gotion insists on 180k minimum annual volume commitment.',
          reasonZh: '由于安亭工厂产能爬坡延误，协商的量价折扣被追回。国轩高科坚持18万辆年最低量承诺。',
          effectiveDate: '2026-03-01',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
      ],
    },
    cea: {
      achieved: -6,
      needed: -10,
      status: 'Amber',
      recentEvents: [
        {
          eventId: 'evt-003',
          timestamp: '2026-01-27T14:00:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-unyx-cmp',
          milestone: 'cea-localization-complete',
          milestoneNameEn: 'CEA Localization Complete',
          milestoneNameZh: 'CEA本地化完成',
          scheduledDate: '2025-11-30',
          actualDate: '2026-01-27',
          slipDays: 58,
          estimatedCostImpactPct: 1.5,
          status: 'Delayed',
        },
        {
          eventId: 'evt-020',
          timestamp: '2026-03-08T09:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'xpeng-cea',
          supplierNameEn: 'XPENG (CEA Partner)',
          supplierNameZh: '小鹏汽车（CEA合作方）',
          componentCategory: 'CEA',
          oldCostIndex: 100,
          newCostIndex: 96,
          costDeltaPct: -4,
          reasonCode: 'localization-synergy',
          reasonEn: 'XPENG CEA architecture shared platform costs reduced. VW/XPENG joint validation of wire harness localization achieved 4% unit cost reduction.',
          reasonZh: '小鹏CEA架构共享平台成本降低。大众/小鹏线束本地化联合验证实现4%单位成本降幅。',
          effectiveDate: '2026-03-08',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-021',
          timestamp: '2026-02-18T15:30:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-unyx-cmp',
          milestone: 'cea-phase2-validation',
          milestoneNameEn: 'CEA Phase 2 Validation Start',
          milestoneNameZh: 'CEA第二阶段验证启动',
          scheduledDate: '2026-03-01',
          actualDate: null,
          slipDays: 0,
          estimatedCostImpactPct: 0,
          status: 'On_Track',
        },
      ],
    },
    adas_soc: {
      achieved: -5,
      needed: -8,
      status: 'Amber',
      recentEvents: [
        {
          eventId: 'evt-004',
          timestamp: '2026-02-20T10:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'horizon-robotics',
          supplierNameEn: 'Horizon Robotics',
          supplierNameZh: '地平线机器人',
          componentCategory: 'ADAS_SoC',
          oldCostIndex: 100,
          newCostIndex: 98,
          costDeltaPct: -2,
          reasonCode: 'localization-milestone-hit',
          reasonEn: 'Journey 6 SoC volume ramp achieved; tier-2 sourcing discount activated. Horizon confirmed 50k unit commitment at locked price.',
          reasonZh: 'Journey 6 SoC量产爬坡完成，二级供应商采购折扣已激活。地平线确认5万辆锁价承诺。',
          effectiveDate: '2026-02-20',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-022',
          timestamp: '2026-03-05T11:30:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-unyx-cmp',
          milestone: 'adas-l2plus-validation',
          milestoneNameEn: 'ADAS L2+ Highway Pilot Validation',
          milestoneNameZh: 'ADAS L2+高速公路辅助驾驶验证',
          scheduledDate: '2026-04-15',
          actualDate: null,
          slipDays: 0,
          estimatedCostImpactPct: 0,
          status: 'On_Track',
        },
        {
          eventId: 'evt-023',
          timestamp: '2026-01-15T16:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'horizon-robotics',
          supplierNameEn: 'Horizon Robotics',
          supplierNameZh: '地平线机器人',
          componentCategory: 'ADAS_SoC',
          oldCostIndex: 105,
          newCostIndex: 100,
          costDeltaPct: -5,
          reasonCode: 'volume-ramp-discount',
          reasonEn: 'Horizon Journey 6 production cost fell due to fab yield improvement from 72% to 89%. Per-unit SoC cost reduced by ¥180.',
          reasonZh: '地平线Journey 6生产成本因晶圆良率从72%提升至89%而下降。单个SoC成本降低180元。',
          effectiveDate: '2026-01-15',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
      ],
    },
    localModules: {
      achieved: -1,
      needed: -1,
      status: 'Green',
      recentEvents: [
        {
          eventId: 'evt-024',
          timestamp: '2026-02-25T14:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'faw-vw-local',
          supplierNameEn: 'FAW-VW Tier-2 Local Sourcing',
          supplierNameZh: '一汽-大众二级本地化采购',
          componentCategory: 'Local_Modules',
          oldCostIndex: 100,
          newCostIndex: 99,
          costDeltaPct: -1,
          reasonCode: 'local-qualification-complete',
          reasonEn: 'Interior trim module localization complete — Changchun supplier qualified, replacing German import. Saving ¥2,400/unit.',
          reasonZh: '内饰模块本地化完成——长春供应商通过资质认证，替代德国进口。节省2400元/辆。',
          effectiveDate: '2026-02-25',
          program: 'id-unyx-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-025',
          timestamp: '2026-03-12T09:00:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-unyx-cmp',
          milestone: 'local-hvac-qualification',
          milestoneNameEn: 'HVAC Local Supplier Qualification',
          milestoneNameZh: '暖通空调本地供应商资质认证',
          scheduledDate: '2026-03-15',
          actualDate: '2026-03-12',
          slipDays: 0,
          estimatedCostImpactPct: 0,
          status: 'Complete',
        },
      ],
    },
    incentiveHeadwind: +3,
    timingHeadwind: +2,
  },
  recentEvents: [
    {
      eventId: 'evt-005',
      timestamp: '2026-03-10T09:15:00Z',
      type: 'CompetitorPricingEvent',
      competitor: 'byd',
      competitorNameEn: 'BYD',
      competitorNameZh: '比亚迪',
      model: 'byd-atto-3',
      modelNameEn: 'BYD Atto 3',
      modelNameZh: '比亚迪元PLUS',
      priceChangePct: -8,
      affectedVwModels: ['id-unyx', 'id-4'],
      estimatedIncentiveImplicationPct: 1.2,
      effectiveDate: '2026-03-10',
      source: 'market-intelligence',
      sourceZh: '市场情报',
    },
    {
      eventId: 'evt-006',
      timestamp: '2026-03-05T16:00:00Z',
      type: 'NevIncentiveUpdatedEvent',
      model: 'id-unyx',
      modelNameEn: 'ID.UNYX',
      modelNameZh: 'ID.UNYX',
      oldIncentiveLevelPct: 4.2,
      newIncentiveLevelPct: 5.1,
      reasonCode: 'competitive-pressure',
      reasonEn: 'BYD and XPENG pricing moves required defensive incentive increase to protect Q1 volume.',
      reasonZh: '比亚迪和小鹏的定价举措迫使提高激励力度，以保护Q1销量。',
      effectiveDate: '2026-03-05',
      approvedBy: 'china-finance-controller@vw.cn',
    },
    {
      eventId: 'evt-001',
      timestamp: '2026-02-15T08:30:00Z',
      type: 'SupplierCostDriftEvent',
      supplierId: 'gotion-high-tech',
      supplierNameEn: 'Gotion High-Tech',
      supplierNameZh: '国轩高科',
      componentCategory: 'Battery',
      oldCostIndex: 100,
      newCostIndex: 103,
      costDeltaPct: +3,
      reasonCode: 'raw-material-inflation',
      reasonEn: 'Lithium carbonate spot price rose 18% in Q1 2026.',
      reasonZh: '碳酸锂现货价格在2026年Q1上涨18%。',
      effectiveDate: '2026-02-15',
      program: 'id-unyx-cmp',
      inputLanguage: 'ZH',
    },
    {
      eventId: 'evt-003',
      timestamp: '2026-01-27T14:00:00Z',
      type: 'ProgramMilestoneEvent',
      program: 'id-unyx-cmp',
      milestone: 'cea-localization-complete',
      milestoneNameEn: 'CEA Localization Complete',
      milestoneNameZh: 'CEA本地化完成',
      scheduledDate: '2025-11-30',
      actualDate: '2026-01-27',
      slipDays: 58,
      estimatedCostImpactPct: 1.5,
      status: 'Delayed',
    },
    {
      eventId: 'evt-030',
      timestamp: '2026-03-14T10:00:00Z',
      type: 'CompetitorPricingEvent',
      competitor: 'xpeng',
      competitorNameEn: 'XPENG',
      competitorNameZh: '小鹏汽车',
      model: 'xpeng-g6',
      modelNameEn: 'XPENG G6',
      modelNameZh: '小鹏G6',
      priceChangePct: -5,
      affectedVwModels: ['id-unyx'],
      estimatedIncentiveImplicationPct: 0.8,
      effectiveDate: '2026-03-14',
      source: 'dealer-network-intelligence',
      sourceZh: '经销商网络情报',
    },
  ],
  recommendedActions: [
    {
      actionId: 'act-001',
      titleEn: 'Renegotiate Gotion Volume Terms',
      titleZh: '重新谈判国轩高科量价条款',
      descriptionEn: 'Commit to 180k+ unit annual volume for FY2027 in exchange for reinstating the 4% volume discount and locking in lithium index-linked pricing to cap raw material risk. This is the single highest-impact lever: 3pp = €60M/yr savings in 2 weeks.',
      descriptionZh: '承诺2027财年年产量18万辆以上，换取恢复4%量价折扣，并锁定与锂价指数挂钩的定价机制。这是最大杠杆：3个百分点=6000万欧元/年节省，仅需2周。',
      impactPct: 3,
      impactEurM: 60,
      leadTimeWeeks: 2,
      feasibilityScore: 4,
      riskScore: 2,
      dependencies: ['Supply commitment approval from VW AG Procurement Board', 'Anting ramp plan confirmation (Q2 target: 15k/month)'],
      dependenciesZh: ['大众AG采购委员会供应承诺批准', '安亭产能爬坡计划确认（Q2目标：1.5万辆/月）'],
      riskFlags: ['volume-commitment-risk'],
      riskFlagsZh: ['销量承诺风险'],
      marginAtRiskIfSkipped: 0.9,
      status: 'pending',
    },
    {
      actionId: 'act-002',
      titleEn: 'Accelerate CEA Localization Phase 2',
      titleZh: '加速CEA本地化第二阶段',
      descriptionEn: 'Surge VCTC Hefei engineering capacity to close remaining CEA localization gap. Phase 1 slip (58 days) already cost 1.5pp. Phase 2 unlocks XPENG shared-platform savings and tier-2 discounts.',
      descriptionZh: '增派合肥大众技术中心工程产能，弥补CEA本地化缺口。第一阶段延误（58天）已造成1.5个百分点成本。第二阶段将解锁小鹏共享平台节省和二级供应商折扣。',
      impactPct: 2,
      impactEurM: 40,
      leadTimeWeeks: 4,
      feasibilityScore: 3,
      riskScore: 2,
      dependencies: ['VCTC Hefei capacity availability (current: 78% utilized)', 'XPENG joint validation sign-off'],
      dependenciesZh: ['合肥大众技术中心产能可用性（当前利用率：78%）', '小鹏联合验证签署'],
      riskFlags: ['engineering-capacity-constraint'],
      riskFlagsZh: ['工程产能限制'],
      marginAtRiskIfSkipped: 0.5,
      status: 'pending',
    },
    {
      actionId: 'act-003',
      titleEn: 'Reduce Incentive via Feature Rebalancing',
      titleZh: '通过功能再平衡降低激励',
      descriptionEn: 'Mid-cycle ID.UNYX refresh with enhanced smart cockpit (Baidu ERNIE) to justify price positioning and reduce incentive dependency by 0.8pp. BYD and XPENG competitor moves force defensive pricing — this counteracts that.',
      descriptionZh: 'ID.UNYX中期改款搭载增强型智能座舱（百度文心），提升价格支撑力，将激励依赖降低0.8个百分点。比亚迪和小鹏的竞争动作要求被动定价——此举可对冲。',
      impactPct: 1,
      impactEurM: 20,
      leadTimeWeeks: 1,
      feasibilityScore: 4,
      riskScore: 1,
      dependencies: ['Baidu ERNIE API integration readiness', 'Marketing approval for feature messaging'],
      dependenciesZh: ['百度文心API集成就绪', '市场部功能宣传批准'],
      riskFlags: ['margin-at-risk-next-90-days'],
      riskFlagsZh: ['未来90天利润风险'],
      marginAtRiskIfSkipped: 0.3,
      status: 'pending',
    },
    {
      actionId: 'act-004',
      titleEn: 'Dual-Source ADAS via Horizon Tier-2',
      titleZh: '通过地平线二级供应商双源ADAS',
      descriptionEn: 'Leverage Horizon Journey 6 ramp to qualify a second local ADAS SoC supplier. Reduces single-source risk and unlocks 1.5pp. Horizon fab yield improved to 89%, making this commercially viable now.',
      descriptionZh: '借助地平线Journey 6量产爬坡认证第二家本地ADAS芯片供应商。降低单一供应商风险并解锁1.5个百分点。地平线晶圆良率已升至89%，现在商业上可行。',
      impactPct: 1.5,
      impactEurM: 30,
      leadTimeWeeks: 8,
      feasibilityScore: 2,
      riskScore: 3,
      dependencies: ['Horizon tier-2 qualification process (8-week cycle)', 'Engineering validation sign-off from VCTC'],
      dependenciesZh: ['地平线二级供应商资质认证流程（8周周期）', '合肥大众技术中心工程验证签署'],
      riskFlags: ['technical-risk', 'supply-chain-risk'],
      riskFlagsZh: ['技术风险', '供应链风险'],
      marginAtRiskIfSkipped: 0.4,
      status: 'pending',
    },
  ],
  countdownMilestones: [
    {
      id: 'cm-001',
      titleEn: 'Gotion Volume Terms Decision',
      titleZh: '国轩高科量价条款决策',
      targetDate: '2026-04-01',
      impactPct: 3,
      impactEurM: 60,
      status: 'at_risk',
      ownerEn: 'VW AG Procurement Board',
      ownerZh: '大众AG采购委员会',
      driverKey: 'battery',
    },
    {
      id: 'cm-002',
      titleEn: 'CEA Phase 2 Validation Complete',
      titleZh: 'CEA第二阶段验证完成',
      targetDate: '2026-05-15',
      impactPct: 2,
      impactEurM: 40,
      status: 'on_track',
      ownerEn: 'VCTC Hefei',
      ownerZh: '合肥大众技术中心',
      driverKey: 'cea',
    },
    {
      id: 'cm-003',
      titleEn: 'ADAS L2+ Highway Pilot Sign-Off',
      titleZh: 'ADAS L2+高速公路辅助驾驶签署',
      targetDate: '2026-04-15',
      impactPct: 1,
      impactEurM: 20,
      status: 'on_track',
      ownerEn: 'Horizon Robotics / VCTC',
      ownerZh: '地平线 / 合肥大众技术中心',
      driverKey: 'adas_soc',
    },
    {
      id: 'cm-004',
      titleEn: 'Smart Cockpit Refresh Launch',
      titleZh: '智能座舱改款发布',
      targetDate: '2026-04-30',
      impactPct: 1,
      impactEurM: 20,
      status: 'on_track',
      ownerEn: 'China Marketing / Baidu',
      ownerZh: '中国市场部 / 百度',
      driverKey: 'cea',
    },
  ],
};

// ─── ID.CODE Program ──────────────────────────────────────────────────────────

const ID_CODE: ChinaCmpProgramSnapshot = {
  program: 'id-code-cmp',
  programNameEn: 'ID.CODE CMP',
  programNameZh: 'ID.CODE 成本平价计划',
  targetCostReductionPct: 40,
  currentCostReductionPct: 19,
  gapPct: 21,
  gapEurM: 21 * EUR_PER_PP,
  status: 'Red',
  varianceLast30Days: -2.5,
  marginAtRisk90Days: 3.1,
  marginAtRiskEurM: 3.1 * EUR_PER_PP,
  sopDate: '2027-03-01',
  biggestLeverEn: 'CATL negotiation escalation — the 8pp battery gap is 38% of the total program gap. Board-level intervention needed immediately.',
  biggestLeverZh: '宁德时代谈判升级——8个百分点的电池缺口占项目总缺口的38%。需要立即进行董事会层面介入。',
  lastUpdated: '2026-03-14T14:00:00Z',
  costDriverBreakdown: {
    battery: {
      achieved: -4,
      needed: -12,
      status: 'Red',
      recentEvents: [
        {
          eventId: 'evt-010',
          timestamp: '2026-03-01T10:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'catl',
          supplierNameEn: 'CATL',
          supplierNameZh: '宁德时代',
          componentCategory: 'Battery',
          oldCostIndex: 100,
          newCostIndex: 105,
          costDeltaPct: +5,
          reasonCode: 'contract-renegotiation-failed',
          reasonEn: 'CATL contract renegotiation stalled — volume terms not agreed for ID.CODE platform. CATL demanding 250k minimum annual commitment.',
          reasonZh: '宁德时代合同重新谈判陷入僵局——ID.CODE平台量价条款未达成一致。宁德时代要求25万辆年最低承诺。',
          effectiveDate: '2026-03-01',
          program: 'id-code-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-040',
          timestamp: '2026-02-10T08:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'catl',
          supplierNameEn: 'CATL',
          supplierNameZh: '宁德时代',
          componentCategory: 'Battery',
          oldCostIndex: 98,
          newCostIndex: 100,
          costDeltaPct: +2,
          reasonCode: 'sodium-ion-delay',
          reasonEn: 'CATL sodium-ion battery qualification for ID.CODE delayed 3 months. Falls back to higher-cost LFP cells, reversing planned 2pp cost reduction.',
          reasonZh: '宁德时代钠离子电池ID.CODE平台资质认证延迟3个月。退回高成本磷酸铁锂电芯，逆转了计划中的2个百分点成本降幅。',
          effectiveDate: '2026-02-10',
          program: 'id-code-cmp',
          inputLanguage: 'ZH',
        },
      ],
    },
    cea: {
      achieved: -5,
      needed: -10,
      status: 'Amber',
      recentEvents: [
        {
          eventId: 'evt-041',
          timestamp: '2026-02-20T14:00:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-code-cmp',
          milestone: 'cea-id-code-design-freeze',
          milestoneNameEn: 'CEA ID.CODE Design Freeze',
          milestoneNameZh: 'CEA ID.CODE设计冻结',
          scheduledDate: '2026-02-15',
          actualDate: null,
          slipDays: 14,
          estimatedCostImpactPct: 0.5,
          status: 'At_Risk',
        },
        {
          eventId: 'evt-042',
          timestamp: '2026-03-10T10:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'xpeng-cea',
          supplierNameEn: 'XPENG (CEA Partner)',
          supplierNameZh: '小鹏汽车（CEA合作方）',
          componentCategory: 'CEA',
          oldCostIndex: 102,
          newCostIndex: 98,
          costDeltaPct: -4,
          reasonCode: 'shared-platform-savings',
          reasonEn: 'XPENG shared CEA platform yields 4% cost reduction on wire harness and ECU modules. ID.CODE benefits from ID.UNYX learnings.',
          reasonZh: '小鹏共享CEA平台在线束和ECU模块上实现4%成本降幅。ID.CODE受益于ID.UNYX经验。',
          effectiveDate: '2026-03-10',
          program: 'id-code-cmp',
          inputLanguage: 'ZH',
        },
      ],
    },
    adas_soc: {
      achieved: -6,
      needed: -8,
      status: 'Green',
      recentEvents: [
        {
          eventId: 'evt-043',
          timestamp: '2026-03-05T09:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'horizon-robotics',
          supplierNameEn: 'Horizon Robotics',
          supplierNameZh: '地平线机器人',
          componentCategory: 'ADAS_SoC',
          oldCostIndex: 95,
          newCostIndex: 92,
          costDeltaPct: -3,
          reasonCode: 'journey7-early-access',
          reasonEn: 'Horizon Journey 7 early-access pricing secured for ID.CODE. Next-gen SoC 15% cheaper than Journey 6 at equivalent performance.',
          reasonZh: '地平线Journey 7为ID.CODE提供早期接入定价。下一代SoC在同等性能下比Journey 6便宜15%。',
          effectiveDate: '2026-03-05',
          program: 'id-code-cmp',
          inputLanguage: 'ZH',
        },
        {
          eventId: 'evt-044',
          timestamp: '2026-02-28T11:00:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-code-cmp',
          milestone: 'adas-journey7-qualification',
          milestoneNameEn: 'Journey 7 SoC Qualification Start',
          milestoneNameZh: 'Journey 7 SoC资质认证启动',
          scheduledDate: '2026-03-01',
          actualDate: '2026-02-28',
          slipDays: 0,
          estimatedCostImpactPct: 0,
          status: 'Complete',
        },
      ],
    },
    localModules: {
      achieved: -4,
      needed: -4,
      status: 'Green',
      recentEvents: [
        {
          eventId: 'evt-045',
          timestamp: '2026-02-15T16:00:00Z',
          type: 'ProgramMilestoneEvent',
          program: 'id-code-cmp',
          milestone: 'local-modules-100pct',
          milestoneNameEn: 'Local Modules 100% Sourced',
          milestoneNameZh: '本地化模块100%采购完成',
          scheduledDate: '2026-02-28',
          actualDate: '2026-02-15',
          slipDays: 0,
          estimatedCostImpactPct: 0,
          status: 'Complete',
        },
        {
          eventId: 'evt-046',
          timestamp: '2026-01-20T10:00:00Z',
          type: 'SupplierCostDriftEvent',
          supplierId: 'faw-vw-local',
          supplierNameEn: 'FAW-VW Tier-2 Local Sourcing',
          supplierNameZh: '一汽-大众二级本地化采购',
          componentCategory: 'Local_Modules',
          oldCostIndex: 101,
          newCostIndex: 96,
          costDeltaPct: -5,
          reasonCode: 'full-localization-achieved',
          reasonEn: 'All 12 previously imported module categories now locally sourced. Average 18% unit cost reduction vs German imports.',
          reasonZh: '此前12个进口模块类别现已全部实现本地化采购。相比德国进口平均单位成本降幅18%。',
          effectiveDate: '2026-01-20',
          program: 'id-code-cmp',
          inputLanguage: 'ZH',
        },
      ],
    },
    incentiveHeadwind: +5,
    timingHeadwind: +4,
  },
  recentEvents: [
    {
      eventId: 'evt-010',
      timestamp: '2026-03-01T10:00:00Z',
      type: 'SupplierCostDriftEvent',
      supplierId: 'catl',
      supplierNameEn: 'CATL',
      supplierNameZh: '宁德时代',
      componentCategory: 'Battery',
      oldCostIndex: 100,
      newCostIndex: 105,
      costDeltaPct: +5,
      reasonCode: 'contract-renegotiation-failed',
      reasonEn: 'CATL contract renegotiation stalled for ID.CODE platform.',
      reasonZh: 'ID.CODE平台宁德时代合同重新谈判陷入僵局。',
      effectiveDate: '2026-03-01',
      program: 'id-code-cmp',
      inputLanguage: 'ZH',
    },
    {
      eventId: 'evt-011',
      timestamp: '2026-02-28T16:00:00Z',
      type: 'ProgramMilestoneEvent',
      program: 'id-code-cmp',
      milestone: 'battery-sourcing-finalized',
      milestoneNameEn: 'Battery Sourcing Finalized',
      milestoneNameZh: '电池供应商确认',
      scheduledDate: '2026-01-15',
      actualDate: null,
      slipDays: 120,
      estimatedCostImpactPct: 2.5,
      status: 'At_Risk',
    },
    {
      eventId: 'evt-050',
      timestamp: '2026-03-12T14:00:00Z',
      type: 'CompetitorPricingEvent',
      competitor: 'nio',
      competitorNameEn: 'NIO',
      competitorNameZh: '蔚来',
      model: 'nio-el8',
      modelNameEn: 'NIO EL8',
      modelNameZh: '蔚来EL8',
      priceChangePct: -6,
      affectedVwModels: ['id-code'],
      estimatedIncentiveImplicationPct: 0.9,
      effectiveDate: '2026-03-12',
      source: 'NIO official announcement',
      sourceZh: '蔚来官方公告',
    },
    {
      eventId: 'evt-051',
      timestamp: '2026-03-08T09:00:00Z',
      type: 'NevIncentiveUpdatedEvent',
      model: 'id-code',
      modelNameEn: 'ID.CODE',
      modelNameZh: 'ID.CODE',
      oldIncentiveLevelPct: 6.0,
      newIncentiveLevelPct: 7.5,
      reasonCode: 'pre-launch-positioning',
      reasonEn: 'Pre-launch incentive positioning increased to build anticipation. NIO and Li Auto competitor pricing forced stronger dealer margin support.',
      reasonZh: '上市前激励定位提升以积聚声量。蔚来和理想的竞争定价迫使加强经销商利润支持。',
      effectiveDate: '2026-03-08',
      approvedBy: 'china-cfo@vw.cn',
    },
  ],
  recommendedActions: [
    {
      actionId: 'act-010',
      titleEn: 'Escalate CATL Negotiation to Board',
      titleZh: '将宁德时代谈判升级至董事会',
      descriptionEn: 'Deadlock on CATL volume terms requires board-level intervention. Alternative: dual-source with Gotion to create leverage. The 8pp battery gap is 38% of total program gap — this is the critical path.',
      descriptionZh: '宁德时代量价条款僵局需要董事会层面介入。备选：与国轩高科双供以创造筹码。8个百分点电池缺口占项目总缺口38%——这是关键路径。',
      impactPct: 5,
      impactEurM: 100,
      leadTimeWeeks: 3,
      feasibilityScore: 3,
      riskScore: 3,
      dependencies: ['VW AG Procurement Board meeting (next: Apr 8)', 'Gotion qualification for ID.CODE platform'],
      dependenciesZh: ['大众AG采购委员会会议（下次：4月8日）', '国轩高科ID.CODE平台资质认证'],
      riskFlags: ['supply-chain-risk', 'relationship-risk'],
      riskFlagsZh: ['供应链风险', '供应商关系风险'],
      marginAtRiskIfSkipped: 1.8,
      status: 'pending',
    },
    {
      actionId: 'act-011',
      titleEn: 'Fast-Track ID.CODE SOP by 2 Months',
      titleZh: '快速通道将ID.CODE SOP提前2个月',
      descriptionEn: 'Compress validation at VCTC Hefei. Reduces timing headwind by 1.5pp (€30M) and enables earlier volume ramp to improve CATL bargaining position.',
      descriptionZh: '压缩合肥大众技术中心验证周期。减少1.5个百分点（3000万欧元）时间headwind，促进更早量产以改善宁德时代谈判地位。',
      impactPct: 3,
      impactEurM: 60,
      leadTimeWeeks: 6,
      feasibilityScore: 2,
      riskScore: 3,
      dependencies: ['VCTC Hefei bandwidth allocation', 'Regulatory homologation timeline flexibility'],
      dependenciesZh: ['合肥大众技术中心带宽分配', '法规认证时间表灵活性'],
      riskFlags: ['engineering-risk', 'regulatory-risk'],
      riskFlagsZh: ['工程风险', '法规风险'],
      marginAtRiskIfSkipped: 1.0,
      status: 'pending',
    },
  ],
  countdownMilestones: [
    {
      id: 'cm-010',
      titleEn: 'CATL Board Escalation Meeting',
      titleZh: '宁德时代董事会升级会议',
      targetDate: '2026-04-08',
      impactPct: 5,
      impactEurM: 100,
      status: 'at_risk',
      ownerEn: 'VW AG Procurement Board',
      ownerZh: '大众AG采购委员会',
      driverKey: 'battery',
    },
    {
      id: 'cm-011',
      titleEn: 'Gotion ID.CODE Qualification',
      titleZh: '国轩高科ID.CODE平台资质认证',
      targetDate: '2026-05-01',
      impactPct: 3,
      impactEurM: 60,
      status: 'on_track',
      ownerEn: 'VCTC Hefei Battery Lab',
      ownerZh: '合肥大众技术中心电池实验室',
      driverKey: 'battery',
    },
    {
      id: 'cm-012',
      titleEn: 'CEA Design Freeze Sign-Off',
      titleZh: 'CEA设计冻结签署',
      targetDate: '2026-03-30',
      impactPct: 2,
      impactEurM: 40,
      status: 'at_risk',
      ownerEn: 'XPENG / VW Joint Team',
      ownerZh: '小鹏/大众联合团队',
      driverKey: 'cea',
    },
    {
      id: 'cm-013',
      titleEn: 'Journey 7 SoC Validation Complete',
      titleZh: 'Journey 7 SoC验证完成',
      targetDate: '2026-06-01',
      impactPct: 1.5,
      impactEurM: 30,
      status: 'on_track',
      ownerEn: 'Horizon Robotics',
      ownerZh: '地平线机器人',
      driverKey: 'adas_soc',
    },
  ],
};

// ─── Export ───────────────────────────────────────────────────────────────────

export const CHINA_CMP_PROGRAMS: ChinaCmpProgramSnapshot[] = [ID_UNYX, ID_CODE];
export const EUR_PER_PP_CONSTANT = EUR_PER_PP;
